RazorTemplateAssignment/Models/ErrorViewModel.cs
namespace RazorTemplateAssignment.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RazorTemplateAssignment/Models/Student.cs
namespace RazorTemplateAssignment.Models
{
    public class Student
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Grade { get; set; }
    }
}

RazorTemplateAssignment/Models/StudentViewModel.cs
namespace RazorTemplateAssignment.Models
{
    public class StudentViewModel
    {
        public List<Student> Students { get; set; }
        public int AccessLevel { get; set; }
    }
}

RazorTemplateAssignment/Controllers/Assignment6Controller.cs
using Microsoft.AspNetCore.Mvc;
using RazorTemplateAssignment.Models;

namespace RazorTemplateAssignment.Controllers
{
    public class Assignment6Controller : Controller
    {
        public IActionResult Index(int accessLevel = 1)
        {
            var students = new List<Student> 
            { 
                new Student {FirstName = "Jared", LastName = "Brannen", Grade = "A"},
                new Student {FirstName = "Lebron", LastName = "James", Grade = "B"},
                new Student {FirstName = "Robert", LastName = "Downey Jr.", Grade = "F"}
            };

            var studentViewModel = new StudentViewModel
            {
                Students = students,
                AccessLevel = accessLevel
            };

            return View(studentViewModel);
        }
    }
}

RazorTemplateAssignment/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using RazorTemplateAssignment.Models;

namespace RazorTemplateAssignment.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

RazorTemplateAssignment/Views/Assignment6/Index.cshtml
@model RazorTemplateAssignment.Models.StudentViewModel

<h1>Assignment 6.1</h1>

@if(Model.AccessLevel < 2)
{
    <p>You don't have an access level that is allowed to see this page.</p>
}
else
{
    @if(Model.AccessLevel >= 8)
    {
        <h2>Hello Admin!</h2>
    }
    <table class="table">
        <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                @if(Model.AccessLevel >= 8)
                {
                    <th>Grade</th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach (var student in Model.Students)
            {
                ViewBag.ShowGrade = Model.AccessLevel >= 8;
                <partial name="_PartialView" model="student" />
            }
        </tbody>
    </table>
}

RazorTemplateAssignment/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RazorTemplateAssignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RazorTemplateAssignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RazorTemplateAssignment.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RazorTemplateAssignment</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" id="assignmentDropdown" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Assignments<span class="caret"></span></a>
                            <ul class="dropdown-menu" aria-labelledby="assignmentDropdown">
                                <li><a class="dropdown-item" asp-controller="Assignment6" asp-action="Index" asp-route-accessLevel="1">Assignment 6.1</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - RazorTemplateAssignment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RazorTemplateAssignment/Views/Shared/_PartialView.cshtml
@model RazorTemplateAssignment.Models.Student


<tr>
    <td>@Model.FirstName</td>
    <td>@Model.LastName</td>
    @if (ViewBag.ShowGrade != null && (bool)ViewBag.ShowGrade)
    {
        <td>@Model.Grade</td>
    }
</tr>