TicketApplication/Models/ErrorViewModel.cs
namespace TicketApplication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TicketApplication/Models/Ticket.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TicketApplication.Models
{
    public class Ticket
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please enter a name.")]
        [StringLength(50, ErrorMessage = "Name cannot be longer than 50 characters.")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter a description")]
        [StringLength(500, ErrorMessage = "Description cannot be longer than 500 characters.")]
        public string Description { get; set; }
        [Range(1, int.MaxValue, ErrorMessage = "Please enter a sprint number with at least a value of 1.")]
        public int SprintNumber { get; set; }
        [Range(1, 50, ErrorMessage = "Please enter a point number between 1 and 50")]
        public int PointValue { get; set; }
        [Required(ErrorMessage = "Status for the ticket is required.")]
        public int TicketStatusId { get; set; }
        [ForeignKey("TicketStatusId")]
        public TicketStatus? Status { get; set; }
    }

}

TicketApplication/Models/TicketContext.cs
using Microsoft.EntityFrameworkCore;

namespace TicketApplication.Models
{
    public class TicketContext : DbContext
    {
        public TicketContext(DbContextOptions<TicketContext> options)
            : base(options)
        {
        }
        public DbSet<Ticket> Tickets { get; set; }
        public DbSet<TicketStatus> TicketStatuses { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Ticket>().HasData(
                new Ticket
                {
                    Id = 1,
                    Name = "Create a new project",
                    Description = "Create a new project in Visual Studio",
                    SprintNumber = 1,
                    PointValue = 3,
                    TicketStatusId = 1
                },
                new Ticket
                {
                    Id = 2,
                    Name = "Add a new model",
                    Description = "Add a new model to the project",
                    SprintNumber = 1,
                    PointValue = 5,
                    TicketStatusId = 2
                },
                new Ticket
                {
                    Id = 3,
                    Name = "Create a new controller",
                    Description = "Create a new controller in the project",
                    SprintNumber = 1,
                    PointValue = 8,
                    TicketStatusId = 3
                }
            );

            modelBuilder.Entity<TicketStatus>().HasData(
                new TicketStatus
                {
                    Id = 1,
                    Name = "To Do"
                },
                new TicketStatus
                {
                    Id = 2,
                    Name = "In Progress"
                },
                new TicketStatus
                {
                    Id = 3,
                    Name = "Done"
                },
                new TicketStatus
                {
                    Id = 4,
                    Name = "QA"
                }
            );
        }
    }
}

TicketApplication/Models/TicketStatus.cs
namespace TicketApplication.Models
{
    public class TicketStatus
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

TicketApplication/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TicketApplication.Models;
using TicketApplication.Repository;

namespace TicketApplication.Controllers;

public class HomeController : Controller
{
    private readonly ITicketRepository repository;
    public HomeController(ITicketRepository repo)
    {
        repository = repo;
    }

    //private readonly ILogger<HomeController> _logger;

   // public HomeController(ILogger<HomeController> logger)
    //{
       // _logger = logger;
    //}

    public IActionResult Index()
    {
        var tickets = repository.GetAll();
        return View(tickets);
    }

    public IActionResult Add()
    {
        ViewBag.Statuses = new SelectList(repository.GetStatuses(), "Id", "Name");
        return View();
    }
    [HttpPost]
    public IActionResult Add(Ticket ticket)
    {
        if (ModelState.IsValid)
        {
            repository.Add(ticket);
            return RedirectToAction("Index");
        }
        ViewBag.Statuses = new SelectList(repository.GetStatuses(), "Id", "Name", ticket.TicketStatusId);
        return View(ticket);
    }
    public IActionResult Edit(int id)
    {
        var ticket = repository.GetById(id);
        if (ticket == null)
        {
            return NotFound();
        }
        ViewBag.Statuses = new SelectList(repository.GetStatuses(), "Id", "Name", ticket.TicketStatusId);
        return View(ticket);
    }
    [HttpPost]
    public IActionResult Edit(int id,Ticket ticket)
    {
        if (ModelState.IsValid)
        {
            repository.Update(ticket);
            return RedirectToAction("Index");
        }
        ViewBag.Statuses = new SelectList(repository.GetStatuses(), "Id", "Name", ticket.TicketStatusId);
        return View(ticket);
    }
    public IActionResult Delete(int id)
    {
        var ticket = repository.GetById(id);
        if (ticket == null)
        {
            return NotFound();
        }
        return View(ticket);
    }
    [HttpPost]
    public IActionResult Delete(Ticket ticket)
    {
        repository.Delete(ticket.Id);
        return RedirectToAction("Index");
    }
    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

TicketApplication/ViewComponents/TicketStatusViewComponent.cs
using Microsoft.AspNetCore.Mvc;
namespace TicketApplication.ViewComponents
{
    public class TicketStatusViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(string statusName)
        {
            return View("Default", statusName);
        }
    }
}

TicketApplication/Views/Home/Add.cshtml
@model Ticket

<h2>Add a Brand New Ticket</h2>
<div class="form-control">
    <form asp-action="Add" method="post">
        <div class="form-group">
            <label asp-for="Name">Name:</label>
            <input asp-for="Name" type="text" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Description:</label>
            <textarea asp-for="Description" class="form-control mt-2"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Status:</label>
            <select asp-for="TicketStatusId" asp-items="ViewBag.Statuses" class="form-control mt-2">
                <option value="" selected>Select a status</option>
            </select>
            <span asp-validation-for="TicketStatusId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Sprint Number:</label>
            <input asp-for="SprintNumber" type="number" class="form-control mt-2"/>
            <span asp-validation-for="SprintNumber" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Point Value:</label>
            <input asp-for="PointValue" type="number" class="form-control mt-2"/>
            <span asp-validation-for="PointValue" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary mt-3">Add</button>
        <a asp-action="Index" class="btn btn-primary mt-3">Cancel</a>
    </form>
</div>

TicketApplication/Views/Home/Delete.cshtml
@model Ticket

<h2>Delete this Ticket?</h2>
<p>Would you like to delete this ticket?</p>

<table class="table table-bordered table-striped mt-2">
    <tr>
        <th>Name</th>
        <td>@Model.Name</td>
    </tr>
    <tr>
        <th>Description</th>
        <td>@Model.Description</td>
    </tr>
    <tr>
        <th>Sprint Number</th>
        <td>@Model.SprintNumber</td>
    </tr>
    <tr>
        <th>Point Value</th>
        <td>@Model.PointValue</td>
    </tr>
    <tr>
        <th>Status</th>
        <td>@await Component.InvokeAsync("TicketStatus", new {statusName = Model.Status?.Name ?? "Unknown"})</td>
    </tr>
</table>
<form asp-action="Delete">
    <input type="hidden" asp-for="Id" />
    <button type="submit" class="btn btn-danger mt-3">Delete</button>
    <a asp-action="Index" class="btn btn-primary mt-3">Cancel</a>
</form>

TicketApplication/Views/Home/Edit.cshtml
@model Ticket

<h2>Edit Exisiting Ticket</h2>
<div class="form-control">
    <form asp-action="Edit" method="post">
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label>Name:</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Description:</label>
            <textarea asp-for="Description" class="form-control mt-2"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Status:</label>
            <select asp-for="TicketStatusId" asp-items="ViewBag.Statuses" class="form-control mt-2"></select>
            <span asp-validation-for="TicketStatusId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Sprint Number:</label>
            <input asp-for="SprintNumber" type="number" class="form-control mt-2" />
            <span asp-validation-for="SprintNumber" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Point Value:</label>
            <input asp-for="PointValue" type="number" class="form-control mt-2" />
            <span asp-validation-for="PointValue" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary mt-3">Save</button>
        <a asp-action="Index" class="btn btn-primary mt-3">Cancel</a>
    </form>
</div>

TicketApplication/Views/Home/Index.cshtml
@model IEnumerable<Ticket>

<h2>List of Tickets</h2>
<div class="col-sm-10">
    <table class="table table-bordered table-striped mt-2">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Status</th>
                <th>Sprint Number</th>
                <th>Point Value</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var ticket in Model)
            {
                <tr>
                    <td>@ticket.Name</td>
                    <td>@ticket.Description</td>
                    <td>@await Component.InvokeAsync("TicketStatus", new {statusName = ticket.Status?.Name ?? "Unknown"})</td>
                    <td>@ticket.SprintNumber</td>
                    <td>@ticket.PointValue</td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@ticket.Id">Edit</a> |
                        <a asp-action="Delete" asp-route-id="@ticket.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <a asp-action="Add" class="btn btn-primary">Add New Ticket</a>
</div>